---
title: "Lecture 3 Assignment part 2"
author: "James"
date: "1/27/2023"
output:
  word_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---
2.(a)
The procedure of this experiment (pouring kisses onto a table using 10 cups filled with 10 kisses), is the part we have to assume. We have to assume that the trials are independent of each other, therefore the 10 kisses in each cup are not dependent on each other, for example, do the kisses interfere with each other while pouring out or the initial position of the kisses in the cup? Also, we cannot prove that all kisses have the exact same weight and shape. Additionally, in the experiment we are using 10 different cups, we need to assume that the cups have no difference from each other and are also poured onto the table using the same method for all 10 cups poured.

(b)
```{r}
alpha <- 0.05
w <- 39
n <- 100

library(binom)
binom.confint(w,n,conf.level = 1-alpha, methods=c("asymptotic","agresti-coull","wilson","exact","lrt"))
```
Wald interval: (0.294, 0.486), we are 95% confident that the true probability of kisses landing on its base is between 0.294 and 0.486.

Agresti-Coull interval: (0.300, 0.488), we are 95% confident that the true probability of kisses landing on its base is between 0.300 and 0.488.

Wilson interval: (0.300, 0.488), we are 95% confident that the true probability of kisses landing on its base is between 0.300 and 0.488.

Clopper-Pearson interval: (0.294, 0.493), we are 95% confident that the true probability of kisses landing on its base is between 0.294 and 0.493.

LR interval: (0.298, 0.488), we are 95% confident that the true probability of kisses landing on its base is between 0.298 and 0.488.

(c)
I think all confidence intervals are acceptable given the sample size, and by also looking at how close the intervals are of each methods.