---
title: "Lecture 3 Assignment"
author: "James Lee"
date: "1/25/2023"
output:
  word_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---
1.(a)
  1. There are n identical trials, or replicates of the same process. Given that the procedures for recording a success and the trial's outcome are essentially the same across all trials, it would seem reasonable to assume that each trial (cars documented) is equal for recording a success (an alternative fuel automobile). Obviously satisfied as a result.
  
  2. There are two possible outcomes for each trial. Either the vehicle is an alternative fuel vehicle or it is not; these are the two possible outcomes. But not perfect, because mistakes can happen, in this case a computer error or human eye error when determining the result. But, we can assume that each alternative fuel car has been correctly observed. Obviously satisfied as a result.
  
  3. The trials are independent of each other. Each car is examined separately and independently of the others. Obviously satisfied as a result.
  
  4. The probability of success remains constant for each trial. The probability of success, an alternate fuel car passing the intersection is not constant, therefore we would have to assume that the probability of alternate fuel cars is constant across the town. Obviously NOT satisfied as a result. 
  
  5. The random variable of interest W is the number of success, not the individual outcomes. We are not attempting to learn anything about each passing car; instead, we are more interested in the number of alternative fuel cars, or W. Obviously satisfied as a result.

(b)
```{r}
alpha <- 0.05
w <- 14
n <- 125

library(binom)
binom.confint(w,n,conf.level = 1-alpha, methods=c("asymptotic","agresti-coull","wilson","exact"))
```
Wald interval: (0.057, 0.167)
Agresti-Coull interval: (0.067, 0.180)
Wilson interval: (0.068, 0.179)
Clopper-Pearson interval: (0.063, 0.181)

(c)
Yes, it appears that the cars using this intersection during this time have a similar probability of alternative fuel use, compared to the nationwide 8%. We can confirm this by checking if the 8% is inside the confidence intervals, and looking at all four intervals it includes 0.08 in each of its intervals.